export default [
  {
    id: 0,
    registrationDate: '10.01.2022',
    name: 'Иванов Иван Иванович',
    status: 'Менеджер',
    amountOfIncome: '10000',
  },
  {
    id: 1,
    registrationDate: '10.01.2022',
    name: 'Иванов Иван Иванович',
    status: 'Директор',
    amountOfIncome: '10000',
  },
  {
    id: 2,
    registrationDate: '10.01.2022',
    name: 'Иванов Иван Иванович',
    status: 'Региональный директор',
    amountOfIncome: '10000',
  },
  {
    id: 3,
    registrationDate: '10.01.2022',
    name: 'Иванов Иван Иванович',
    status: 'Федеральный директор',
    amountOfIncome: '10000',
  },
  {
    id: 4,
    registrationDate: '10.01.2022',
    name: 'Иванов Иван Иванович',
    status: 'Генеральный директор',
    amountOfIncome: '10000',
  },
  {
    id: 5,
    registrationDate: '10.01.2022',
    name: 'Иванов Иван Иванович',
    status: 'Собственник',
    amountOfIncome: '10000',
  },
  {
    id: 6,
    registrationDate: '10.01.2022',
    name: 'Иванов Иван Иванович',
    status: 'Менеджер',
    amountOfIncome: '10000',
  },
  {
    id: 7,
    registrationDate: '10.01.2022',
    name: 'Иванов Иван Иванович',
    status: 'Менеджер',
    amountOfIncome: '10000',
  },
  {
    id: 8,
    registrationDate: '10.01.2022',
    name: 'Иванов Иван Иванович',
    status: 'Менеджер',
    amountOfIncome: '10000',
  },
  {
    id: 9,
    registrationDate: '10.01.2022',
    name: 'Иванов Иван Иванович',
    status: 'Менеджер',
    amountOfIncome: '10000',
  },
  {
    id: 10,
    registrationDate: '10.01.2022',
    name: 'Иванов Иван Иванович',
    status: 'Менеджер',
    amountOfIncome: '10000',
  },
  {
    id: 11,
    registrationDate: '10.01.2022',
    name: 'Иванов Иван Иванович',
    status: 'Менеджер',
    amountOfIncome: '10000',
  },
  {
    id: 12,
    registrationDate: '10.01.2022',
    name: 'Иванов Иван Иванович',
    status: 'Менеджер',
    amountOfIncome: '10000',
  },
  {
    id: 13,
    registrationDate: '10.01.2022',
    name: 'Иванов Иван Иванович',
    status: 'Менеджер',
    amountOfIncome: '10000',
  },
  {
    id: 14,
    registrationDate: '10.01.2022',
    name: 'Иванов Иван Иванович',
    status: 'Менеджер',
    amountOfIncome: '10000',
  },
  {
    id: 15,
    registrationDate: '10.01.2022',
    name: 'Иванов Иван Иванович',
    status: 'Менеджер',
    amountOfIncome: '10000',
  },
  {
    id: 16,
    registrationDate: '10.01.2022',
    name: 'Иванов Иван Иванович',
    status: 'Менеджер',
    amountOfIncome: '10000',
  },
]
